### ISSUE TITLE
Keyboard layout of restored qubes stuck

### ISSUE THREAD

**Issue by UndeadDevel** [tasket/wyng-util-qubes#31]
I was going to report this first on the Qubes issue tracker, but it does seem to be `wyng` specific (`wyng` and `wyng-util-qubes` are on the `main` branches; for `wyng`: `prog_date = "20240515"`; the util file was updated the same day):

I had noticed for a few days that there were problems with switching the keyboard layout in some qubes and today investigated: the keyboard layout will not change from its default in all qubes that were restored from `wyng`, with the exception of the `gpg-vault` qube, which was restored with an error (`wyng-util-qubes` crashed, reported in #25). VMs restored from my regular Qubes backup (`qvm-backup`) and VMs not restored at all have no such issue. Deleting an affected qube and restoring with `wyng-util-qubes` again does not fix the problem; backing up the qube with the regular qubes tools, deleting it and restoring it with the regular qubes tools does not fix the issue; only restoring from my last big regular `qvm-backup` backup fixes the issue. I didn't have any keyboard layout issues like this ever since I upgraded to QubesOS 4.2, so for >6 months and, as stated, only those qubes which I restored with `wyng` have the issue, so it's very likely due to `wyng` (or `wyng-util-qubes`).

So I'm likely going to have to create new qubes and manually move the user data from the affected ones over unless you have an idea of how to fix this...can `wyng` tell me which files are different between two sessions?

**Comment by tasket** [comment]
I tried to reproduce the problem by setting a vm's `keyboard_layout` pref to something other than the system default. Then I used `wyng-util-qubes backup vmname` to back it up. Next I deleted the vm from the system with `qvm-remove` and finally I restored it.  The vm with correct `keyboard_layout` setting was restored without errors.

I suggest trying a restore and checking that pref with `qvm-prefs` both before and after the restore.  In the worst case, you should be able to set the keyboard pref manually with `qvm-prefs` instead of having to create new vms and then moving the data.

In the past there have been problems with Qubes prefs not being saved unless the pref was set twice with a delay in between; in that case Qubes was not responding correctly to changes in settings. As with the spot test you did with `qvm-backup`, even the Qubes-supplied tools might not handle vm settings correctly.

**Comment by tasket** [comment]
BTW, you can use `--debug` on the util command line and when it gets to the prefs setting part, each pref and its value will be displayed.

**Comment by UndeadDevel** [comment]
To clarify: the `keyboard_layout` value does change when I change the keyboard layout and the qube is not affected; the issue is that the keyboard layout change does not propagate to affected qubes and restoring a qube from a `wyng` backup somehow makes them be affected / have this bug.

**Comment by tasket** [comment]
@UndeadDevel I'm glad you posted the debug output. The util is setting keyboard_layout to its system default. That would mean there was no particular layout setting for your VM in the 'qubes.xml' at backup time. It does sound like you are using the desktop UI in dom0 to change layouts.

On my test VM, I set the keyboard_layout pref using `qvm-prefs` before backup, and the layout is restored properly. It is not getting set to the system default. Typing in the VM responds correctly to the layout I set.

I can try to change the layout from Qube Manager, but it says the function is unsupported.

And there is very little guidance on [using](https://forum.qubes-os.org/t/using-multiple-keyboard-layouts/19029) keyboard layout in Qubes. @marmarek @DemiMarie can you comment on the disparity on UndeadDevel's machine?

**Comment by UndeadDevel** [comment]
> Restore your test vm with wyng-util-qubes, then qvm-prefs -D vmname keyboard_layout. Does that allow the VM to respond to the layout widget?

That fixes it, thank you! I was hoping there was a way to fix it without having to move all my data to new qubes.

**Comment by tasket** [comment]
@UndeadDevel Good! Then the update in the '09beta' branch should avoid the problem without having to run `qvm-prefs`.
