### ISSUE TITLE
Automatic --remap on "backup"

### ISSUE THREAD

**Issue by tlaurion** [tasket/wyng-util-qubes#5]
Otherwise volumes that were taken care from another meta-dir are not taken into consideration

**Comment by tlaurion** [comment]
I had to use wyng-04wip directly to do a send with --remap --clean like I normally do by habit (to remove .tick .tock of deleted qubes and make sure my send includes newer qubes/templates)

**Comment by tasket** [comment]
I'll probably add --remap directly, but I might also add the ability to pass along "Wyng options".

BTW, as a stopgap you can delete either the _.tick_ lv or the _deltamap_ in the meta dir and that will cause Wyng to remap automatically.

**Comment by tasket** [comment]
@tlaurion I've added `-w` option which lets you pass options directly to Wyng, like so:

```
wyng-util-qubes -w remap -w clean
```

The double-dash option names must be used, but specified without the dashes.

**Comment by tlaurion** [comment]
@tasket my point here, as of for wyng, is that --clean and --remap should probably be there by default.

Unless you have a use case in mind where counter indicted

**Comment by tasket** [comment]
My view is that its better to do these things when its the user's (or calling app's) intention instead of making an assumption inside Wyng.  The short explanation is that Wyng can't make assumptions about the system being non-dynamic (e.g. other processes not doing snapshot rotation, for example).  So 'auto clean' is counter indicated for the core use case:  very large volumes (expensive to scan) that are backed up very frequently (many opportunities for the race condition).

Probably this wrapper can make reliable cleaning decisions based on Qubes db info, but it would be only for VM volumes.

Remap is already done automatically if any snapshot or deltamap goes missing.  But when user is sending a volume to multiple archives, that is definitely a corner case that begs for degraded performance (as opposed to making file-based backups of the backup, which retains efficiency).  So the user or integrator has to make a conscious decision to defeat Wyng's core feature.  Wyng also has most of the needed infra to do differential archive-to-archive updates efficiently, so that could be another option for this use case in the future.
